### ISSUE TITLE
Define a data format for CEN reports.

### ISSUE THREAD

**Issue by hdevalence** [Co-Epi/CEN#17]
These reports will be collected by the backend, randomized, and collected into a static file pushed to a CDN.  It's important to make each report as compact as possible, because it will be downloaded by every client.

Some of the details of the report data are set by the exact mechanism for CEN generation, but others seem less clear (to me).  In particular, if the protocol is supposed to be relatively application-agnostic, it seems important to have flexibility regarding the report contents built in from the beginning, because there will be no opportunity to change it later.

Should the report contents just be length-delimited binary data? What information is needed to distinguish symptom reports from infection reports? What if there are multiple entities (e.g., different health authorities) who produce infection reports?

**Comment by sourabhniyogi** [comment]
Hamish Rodda has a very COVID-19 specific design (see data models repo) with a nested structure (temperature, spO2) to approximate the way a real doctor (as he is) would approach it.  There is no way a free text system is a good idea, but most of Hamish's approach can be mapped into language-independent "symptom concept" flags (where symptom space is approximated by integers that can be mapped back into a persons native language) and an expanding array of presumably genetically sequencable diseaseID (you can have rabies, you can have rabies A, or rabies B, or rabies C).    In a federated model of CEN servers, the CEN reports would then have a set of integer bits for both symptoms and diseases and the readers of the data would then query a dictionary to map symptom and disease concepts.  

There are many health standards already and ideally we would just be able to shop for something but this is a _novel_ corona virus so we would like a specific mechanism for it to be somehow have been creatable without a standards body by someone in Dec 2019-Jan 2019 rather than well after that.

**Comment by hdevalence** [comment]
The memo format in #20 can encode small chunks of arbitrary data, depending on the application, so that different applications can use different encodings, as works for them. In the worst case, if some application needs to encode a large amount of data for some reason, they can encode an ID into the broadcast that their client can use to fetch the body of the message.

**Comment by hdevalence** [comment]
Closing as resolved by the current report format.
